# -*- coding: utf-8 -*-
"""Exercicio_num.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RIkfOcU1bvYGF315rgXmKOEM24Jme28I
"""

#Faça um programa que recebe a largura e altura de uma parede em centímetros e o rendimento de uma determinada tinta medido em m2/litro e calcule quantos litros de tinta serão necessários para pintá-la com duas demãos.

a = float(input('Informe a altura da parede em centímetros: '))
l = float(input('Informe a largura da parede em centímetros: '))

p = (a*l)/10000
print('A parede tem a M² de : ', p , 'm²')
r = float(input('Informe o rendimento da tinta: '  , 'm²'))
rend = r

#Faça um programa que sugere jogos da mega-sena. O programa pedirá ao usuário a quantidade de jogos que ele quer fazer e gera os números de cada cartão. Utilize a biblioteca "random" para resolver o problema.
from random import sample
jogos = int(input('Quantos cartões de 06 dezenas deseja jogar?'))
cartoes = [sample(range(1,61),6) for _ in range(jogos)]
for i,c in enumerate(cartoes):
  print(f'Cartão {i+1}: {c}')

#Faça um programa que implementa o jogo "Pedra-papel-Tesoura" entre o usuário e o computador. O programa pede a opção do usuário e a opção do computador é escolhida aleatoriamente. 
# O jogo continua até que o usuário escolha sair. Ao sair, o programa imprime o resultado final das partidas.
from random import randint
score = {'jogador': 0,'computador': 0}
itens = ('Pedra', 'Papel', 'Tesoura')

while True:
  jogador = int(input("""  [0] - Pedra
  [1] - Papel
  [2] - Tesoura
  Escolha a opção desejada: """))
  if jogador > 2 or jogador < 0:
    print('opção inválida')
    continue
  computador = randint(0,2)

  print(f"Jogador jogou {itens[jogador]}")
  print(f"Computador jogou {itens[computador]}")

  if jogador == computador:
    print('Empate!')
  elif jogador == 1 and computador == 0:
    print('Jogador Ganhou!')
    score['jogador'] += 1
  elif jogador == 2 and computador == 1:
    print('Jogador Ganhou!')
    score['jogador'] += 1  
  elif jogador == 0 and computador == 2:
    print('Jogador Ganhou!')
    score['jogador'] += 1
  else:
    print('Computador Ganhou!')
    score['computador'] += 1

  if input('Deseja continuar (S/N)?') == 'n':
    print(50*'=')
    print('Resultado')
    print(f"Jogador ganhou {score['jogador']}")
    print(f"Computador ganhou {score['computador']}")
    break

